// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/data/migration_v6_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:phf/core/security/master_key_manager.dart' as _i3;
import 'package:phf/core/services/path_provider_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MasterKeyManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMasterKeyManager extends _i1.Mock implements _i3.MasterKeyManager {
  @override
  _i4.Future<_i5.Uint8List> getMasterKey() => (super.noSuchMethod(
        Invocation.method(
          #getMasterKey,
          [],
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<_i5.Uint8List> getUserSalt() => (super.noSuchMethod(
        Invocation.method(
          #getUserSalt,
          [],
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> wipeAll() => (super.noSuchMethod(
        Invocation.method(
          #wipeAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PathProviderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathProviderService extends _i1.Mock
    implements _i6.PathProviderService {
  @override
  String get sandboxRoot => (super.noSuchMethod(
        Invocation.getter(#sandboxRoot),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#sandboxRoot),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#sandboxRoot),
        ),
      ) as String);

  @override
  String get dbDirPath => (super.noSuchMethod(
        Invocation.getter(#dbDirPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#dbDirPath),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#dbDirPath),
        ),
      ) as String);

  @override
  String get imagesDirPath => (super.noSuchMethod(
        Invocation.getter(#imagesDirPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#imagesDirPath),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#imagesDirPath),
        ),
      ) as String);

  @override
  String get tempDirPath => (super.noSuchMethod(
        Invocation.getter(#tempDirPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#tempDirPath),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#tempDirPath),
        ),
      ) as String);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getDatabasePath(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #getDatabasePath,
          [fileName],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDatabasePath,
            [fileName],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDatabasePath,
            [fileName],
          ),
        ),
      ) as String);

  @override
  _i4.Future<_i2.File> getSecureFile(String? relativePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecureFile,
          [relativePath],
        ),
        returnValue: _i4.Future<_i2.File>.value(_FakeFile_0(
          this,
          Invocation.method(
            #getSecureFile,
            [relativePath],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.File>.value(_FakeFile_0(
          this,
          Invocation.method(
            #getSecureFile,
            [relativePath],
          ),
        )),
      ) as _i4.Future<_i2.File>);

  @override
  _i4.Future<void> clearTemp() => (super.noSuchMethod(
        Invocation.method(
          #clearTemp,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
