include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    todo: info
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # PHF Specific Standards
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - prefer_const_constructors
    - prefer_final_locals
    - unawaited_futures
    - unnecessary_await_in_return
    - use_super_parameters
    
    # Negative Constraints (Ref: Constitution#XII)
    - avoid_print
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state

analyzer_plugin:
  - dart_code_linter

dart_code_linter:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - no-equal-then-else
    - no-object-declaration
    - member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - public-methods
          - private-methods
