// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/data/repositories/ocr_queue_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:phf/core/security/master_key_manager.dart' as _i2;
import 'package:phf/core/services/path_provider_service.dart' as _i3;
import 'package:phf/data/datasources/local/database_service.dart' as _i5;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMasterKeyManager_0 extends _i1.SmartFake
    implements _i2.MasterKeyManager {
  _FakeMasterKeyManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePathProviderService_1 extends _i1.SmartFake
    implements _i3.PathProviderService {
  _FakePathProviderService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SQLCipherDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSQLCipherDatabaseService extends _i1.Mock
    implements _i5.SQLCipherDatabaseService {
  @override
  _i2.MasterKeyManager get keyManager =>
      (super.noSuchMethod(
            Invocation.getter(#keyManager),
            returnValue: _FakeMasterKeyManager_0(
              this,
              Invocation.getter(#keyManager),
            ),
            returnValueForMissingStub: _FakeMasterKeyManager_0(
              this,
              Invocation.getter(#keyManager),
            ),
          )
          as _i2.MasterKeyManager);

  @override
  _i3.PathProviderService get pathService =>
      (super.noSuchMethod(
            Invocation.getter(#pathService),
            returnValue: _FakePathProviderService_1(
              this,
              Invocation.getter(#pathService),
            ),
            returnValueForMissingStub: _FakePathProviderService_1(
              this,
              Invocation.getter(#pathService),
            ),
          )
          as _i3.PathProviderService);

  @override
  String get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#locale),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#locale),
            ),
          )
          as String);

  @override
  _i7.Future<_i4.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i4.Database>.value(
              _FakeDatabase_2(this, Invocation.getter(#database)),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Database>.value(
              _FakeDatabase_2(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i4.Database>);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> onCreate(_i4.Database? db, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#onCreate, [db, version]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
