// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/logic/services/ocr_processor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:phf/core/security/encrypted_file_result.dart' as _i3;
import 'package:phf/core/security/file_security_helper.dart' as _i16;
import 'package:phf/core/services/path_provider_service.dart' as _i17;
import 'package:phf/data/models/image.dart' as _i9;
import 'package:phf/data/models/ocr_queue_item.dart' as _i7;
import 'package:phf/data/models/ocr_result.dart' as _i2;
import 'package:phf/data/models/record.dart' as _i11;
import 'package:phf/data/models/search_result.dart' as _i13;
import 'package:phf/data/repositories/interfaces/image_repository.dart' as _i8;
import 'package:phf/data/repositories/interfaces/ocr_queue_repository.dart'
    as _i5;
import 'package:phf/data/repositories/interfaces/record_repository.dart'
    as _i10;
import 'package:phf/data/repositories/interfaces/search_repository.dart'
    as _i12;
import 'package:phf/logic/services/interfaces/ocr_service.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOcrResult_0 extends _i1.SmartFake implements _i2.OcrResult {
  _FakeOcrResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptedFileResult_1 extends _i1.SmartFake
    implements _i3.EncryptedFileResult {
  _FakeEncryptedFileResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_2 extends _i1.SmartFake implements _i4.File {
  _FakeFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IOCRQueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOCRQueueRepository extends _i1.Mock
    implements _i5.IOCRQueueRepository {
  @override
  _i6.Future<void> enqueue(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [imageId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.OCRQueueItem?> dequeue() =>
      (super.noSuchMethod(
            Invocation.method(#dequeue, []),
            returnValue: _i6.Future<_i7.OCRQueueItem?>.value(),
            returnValueForMissingStub: _i6.Future<_i7.OCRQueueItem?>.value(),
          )
          as _i6.Future<_i7.OCRQueueItem?>);

  @override
  _i6.Future<void> updateStatus(
    String? id,
    _i7.OCRJobStatus? status, {
    String? error,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [id, status], {#error: error}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> incrementRetry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRetry, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getPendingCount({String? personId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCount, [], {#personId: personId}),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> deleteJob(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteJob, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteByImageId(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByImageId, [imageId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [IImageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIImageRepository extends _i1.Mock implements _i8.IImageRepository {
  @override
  _i6.Future<List<_i9.MedicalImage>> getImagesForRecord(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getImagesForRecord, [recordId]),
            returnValue: _i6.Future<List<_i9.MedicalImage>>.value(
              <_i9.MedicalImage>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i9.MedicalImage>>.value(
              <_i9.MedicalImage>[],
            ),
          )
          as _i6.Future<List<_i9.MedicalImage>>);

  @override
  _i6.Future<void> saveImages(List<_i9.MedicalImage>? images) =>
      (super.noSuchMethod(
            Invocation.method(#saveImages, [images]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateImageTags(String? imageId, List<String>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#updateImageTags, [imageId, tagIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteImage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateImageMetadata(
    String? imageId, {
    String? hospitalName,
    DateTime? visitDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateImageMetadata,
              [imageId],
              {#hospitalName: hospitalName, #visitDate: visitDate},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i9.MedicalImage?> getImageById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getImageById, [id]),
            returnValue: _i6.Future<_i9.MedicalImage?>.value(),
            returnValueForMissingStub: _i6.Future<_i9.MedicalImage?>.value(),
          )
          as _i6.Future<_i9.MedicalImage?>);

  @override
  _i6.Future<void> updateOCRData(
    String? imageId,
    String? text, {
    String? rawJson,
    double? confidence = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateOCRData,
              [imageId, text],
              {#rawJson: rawJson, #confidence: confidence},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [IRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRecordRepository extends _i1.Mock implements _i10.IRecordRepository {
  @override
  _i6.Future<List<_i11.MedicalRecord>> getRecordsByPerson(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordsByPerson, [personId]),
            returnValue: _i6.Future<List<_i11.MedicalRecord>>.value(
              <_i11.MedicalRecord>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i11.MedicalRecord>>.value(
                  <_i11.MedicalRecord>[],
                ),
          )
          as _i6.Future<List<_i11.MedicalRecord>>);

  @override
  _i6.Future<_i11.MedicalRecord?> getRecordById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordById, [id]),
            returnValue: _i6.Future<_i11.MedicalRecord?>.value(),
            returnValueForMissingStub: _i6.Future<_i11.MedicalRecord?>.value(),
          )
          as _i6.Future<_i11.MedicalRecord?>);

  @override
  _i6.Future<void> saveRecord(_i11.MedicalRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecord, [record]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateStatus(String? id, _i11.RecordStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [id, status]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateRecordMetadata(
    String? id, {
    String? hospitalName,
    DateTime? visitDate,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRecordMetadata,
              [id],
              {
                #hospitalName: hospitalName,
                #visitDate: visitDate,
                #notes: notes,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> hardDeleteRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteRecord, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.MedicalRecord>> searchRecords({
    required String? personId,
    String? query,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRecords, [], {
              #personId: personId,
              #query: query,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<_i11.MedicalRecord>>.value(
              <_i11.MedicalRecord>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i11.MedicalRecord>>.value(
                  <_i11.MedicalRecord>[],
                ),
          )
          as _i6.Future<List<_i11.MedicalRecord>>);

  @override
  _i6.Future<void> syncRecordMetadata(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#syncRecordMetadata, [recordId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getPendingCount(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCount, [personId]),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i11.MedicalRecord>> getReviewRecords(String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewRecords, [personId]),
            returnValue: _i6.Future<List<_i11.MedicalRecord>>.value(
              <_i11.MedicalRecord>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i11.MedicalRecord>>.value(
                  <_i11.MedicalRecord>[],
                ),
          )
          as _i6.Future<List<_i11.MedicalRecord>>);
}

/// A class which mocks [ISearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISearchRepository extends _i1.Mock implements _i12.ISearchRepository {
  @override
  _i6.Future<List<_i13.SearchResult>> search(String? query, String? personId) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query, personId]),
            returnValue: _i6.Future<List<_i13.SearchResult>>.value(
              <_i13.SearchResult>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i13.SearchResult>>.value(
                  <_i13.SearchResult>[],
                ),
          )
          as _i6.Future<List<_i13.SearchResult>>);

  @override
  _i6.Future<void> updateIndex(String? recordId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#updateIndex, [recordId, content]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncRecordIndex(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#syncRecordIndex, [recordId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteIndex(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIndex, [recordId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [IOCRService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOCRService extends _i1.Mock implements _i14.IOCRService {
  @override
  _i6.Future<_i2.OcrResult> recognizeText(
    _i15.Uint8List? imageBytes, {
    String? mimeType,
    String? language = 'zh',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recognizeText,
              [imageBytes],
              {#mimeType: mimeType, #language: language},
            ),
            returnValue: _i6.Future<_i2.OcrResult>.value(
              _FakeOcrResult_0(
                this,
                Invocation.method(
                  #recognizeText,
                  [imageBytes],
                  {#mimeType: mimeType, #language: language},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.OcrResult>.value(
              _FakeOcrResult_0(
                this,
                Invocation.method(
                  #recognizeText,
                  [imageBytes],
                  {#mimeType: mimeType, #language: language},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.OcrResult>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [FileSecurityHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSecurityHelper extends _i1.Mock
    implements _i16.FileSecurityHelper {
  @override
  _i6.Future<_i3.EncryptedFileResult> encryptMedia(
    _i4.File? sourceFile, {
    required String? targetDir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMedia,
              [sourceFile],
              {#targetDir: targetDir},
            ),
            returnValue: _i6.Future<_i3.EncryptedFileResult>.value(
              _FakeEncryptedFileResult_1(
                this,
                Invocation.method(
                  #encryptMedia,
                  [sourceFile],
                  {#targetDir: targetDir},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.EncryptedFileResult>.value(
                  _FakeEncryptedFileResult_1(
                    this,
                    Invocation.method(
                      #encryptMedia,
                      [sourceFile],
                      {#targetDir: targetDir},
                    ),
                  ),
                ),
          )
          as _i6.Future<_i3.EncryptedFileResult>);

  @override
  _i6.Future<_i3.EncryptedFileResult> saveEncryptedFile({
    required _i15.Uint8List? data,
    required String? targetDir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveEncryptedFile, [], {
              #data: data,
              #targetDir: targetDir,
            }),
            returnValue: _i6.Future<_i3.EncryptedFileResult>.value(
              _FakeEncryptedFileResult_1(
                this,
                Invocation.method(#saveEncryptedFile, [], {
                  #data: data,
                  #targetDir: targetDir,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.EncryptedFileResult>.value(
                  _FakeEncryptedFileResult_1(
                    this,
                    Invocation.method(#saveEncryptedFile, [], {
                      #data: data,
                      #targetDir: targetDir,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.EncryptedFileResult>);

  @override
  _i6.Future<_i4.File> decryptToTemp(
    String? encryptedPath,
    String? base64Key, {
    required String? tempDir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decryptToTemp,
              [encryptedPath, base64Key],
              {#tempDir: tempDir},
            ),
            returnValue: _i6.Future<_i4.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(
                  #decryptToTemp,
                  [encryptedPath, base64Key],
                  {#tempDir: tempDir},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(
                  #decryptToTemp,
                  [encryptedPath, base64Key],
                  {#tempDir: tempDir},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.File>);

  @override
  _i6.Future<_i15.Uint8List> decryptDataFromFile(
    String? path,
    String? base64Key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptDataFromFile, [path, base64Key]),
            returnValue: _i6.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
            returnValueForMissingStub: _i6.Future<_i15.Uint8List>.value(
              _i15.Uint8List(0),
            ),
          )
          as _i6.Future<_i15.Uint8List>);
}

/// A class which mocks [PathProviderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathProviderService extends _i1.Mock
    implements _i17.PathProviderService {
  @override
  String get sandboxRoot =>
      (super.noSuchMethod(
            Invocation.getter(#sandboxRoot),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#sandboxRoot),
            ),
            returnValueForMissingStub: _i18.dummyValue<String>(
              this,
              Invocation.getter(#sandboxRoot),
            ),
          )
          as String);

  @override
  String get dbDirPath =>
      (super.noSuchMethod(
            Invocation.getter(#dbDirPath),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#dbDirPath),
            ),
            returnValueForMissingStub: _i18.dummyValue<String>(
              this,
              Invocation.getter(#dbDirPath),
            ),
          )
          as String);

  @override
  String get imagesDirPath =>
      (super.noSuchMethod(
            Invocation.getter(#imagesDirPath),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#imagesDirPath),
            ),
            returnValueForMissingStub: _i18.dummyValue<String>(
              this,
              Invocation.getter(#imagesDirPath),
            ),
          )
          as String);

  @override
  String get tempDirPath =>
      (super.noSuchMethod(
            Invocation.getter(#tempDirPath),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#tempDirPath),
            ),
            returnValueForMissingStub: _i18.dummyValue<String>(
              this,
              Invocation.getter(#tempDirPath),
            ),
          )
          as String);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  String getDatabasePath(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, [fileName]),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.method(#getDatabasePath, [fileName]),
            ),
            returnValueForMissingStub: _i18.dummyValue<String>(
              this,
              Invocation.method(#getDatabasePath, [fileName]),
            ),
          )
          as String);

  @override
  _i6.Future<_i4.File> getSecureFile(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getSecureFile, [relativePath]),
            returnValue: _i6.Future<_i4.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(#getSecureFile, [relativePath]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(#getSecureFile, [relativePath]),
              ),
            ),
          )
          as _i6.Future<_i4.File>);

  @override
  _i6.Future<void> clearTemp() =>
      (super.noSuchMethod(
            Invocation.method(#clearTemp, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
