// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/core/security/file_security_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phf/logic/services/interfaces/crypto_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ICryptoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockICryptoService extends _i1.Mock implements _i2.ICryptoService {
  @override
  _i3.Uint8List generateRandomKey() => (super.noSuchMethod(
        Invocation.method(
          #generateRandomKey,
          [],
        ),
        returnValue: _i3.Uint8List(0),
        returnValueForMissingStub: _i3.Uint8List(0),
      ) as _i3.Uint8List);

  @override
  _i4.Future<_i3.Uint8List> encrypt({
    required _i3.Uint8List? data,
    required _i3.Uint8List? key,
    _i3.Uint8List? associatedData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [],
          {
            #data: data,
            #key: key,
            #associatedData: associatedData,
          },
        ),
        returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
      ) as _i4.Future<_i3.Uint8List>);

  @override
  _i4.Future<_i3.Uint8List> decrypt({
    required _i3.Uint8List? encryptedData,
    required _i3.Uint8List? key,
    _i3.Uint8List? associatedData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [],
          {
            #encryptedData: encryptedData,
            #key: key,
            #associatedData: associatedData,
          },
        ),
        returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
      ) as _i4.Future<_i3.Uint8List>);

  @override
  _i4.Future<void> encryptFile({
    required String? sourcePath,
    required String? destPath,
    required _i3.Uint8List? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptFile,
          [],
          {
            #sourcePath: sourcePath,
            #destPath: destPath,
            #key: key,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> decryptFile({
    required String? sourcePath,
    required String? destPath,
    required _i3.Uint8List? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptFile,
          [],
          {
            #sourcePath: sourcePath,
            #destPath: destPath,
            #key: key,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
