// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/presentation/pages/timeline/timeline_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phf/data/models/image.dart' as _i7;
import 'package:phf/data/models/record.dart' as _i4;
import 'package:phf/data/models/tag.dart' as _i9;
import 'package:phf/data/repositories/interfaces/image_repository.dart' as _i6;
import 'package:phf/data/repositories/interfaces/record_repository.dart' as _i2;
import 'package:phf/data/repositories/interfaces/tag_repository.dart' as _i8;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRecordRepository extends _i1.Mock implements _i2.IRecordRepository {
  @override
  _i3.Future<void> saveRecord(
    _i4.MedicalRecord? record, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecord, [record], {#executor: executor}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.MedicalRecord?> getRecordById(
    String? id, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecordById, [id], {#executor: executor}),
            returnValue: _i3.Future<_i4.MedicalRecord?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.MedicalRecord?>.value(),
          )
          as _i3.Future<_i4.MedicalRecord?>);

  @override
  _i3.Future<List<_i4.MedicalRecord>> getRecordsByPerson(
    String? personId, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecordsByPerson,
              [personId],
              {#executor: executor},
            ),
            returnValue: _i3.Future<List<_i4.MedicalRecord>>.value(
              <_i4.MedicalRecord>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.MedicalRecord>>.value(
                  <_i4.MedicalRecord>[],
                ),
          )
          as _i3.Future<List<_i4.MedicalRecord>>);

  @override
  _i3.Future<void> updateStatus(
    String? id,
    _i4.RecordStatus? status, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateStatus,
              [id, status],
              {#executor: executor},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateRecordMetadata(
    String? id, {
    String? hospitalName,
    DateTime? visitDate,
    String? notes,
    String? groupId,
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRecordMetadata,
              [id],
              {
                #hospitalName: hospitalName,
                #visitDate: visitDate,
                #notes: notes,
                #groupId: groupId,
                #executor: executor,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> hardDeleteRecord(
    String? id, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteRecord, [id], {#executor: executor}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.MedicalRecord>> searchRecords({
    required String? personId,
    String? query,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRecords, [], {
              #personId: personId,
              #query: query,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
              #executor: executor,
            }),
            returnValue: _i3.Future<List<_i4.MedicalRecord>>.value(
              <_i4.MedicalRecord>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.MedicalRecord>>.value(
                  <_i4.MedicalRecord>[],
                ),
          )
          as _i3.Future<List<_i4.MedicalRecord>>);

  @override
  _i3.Future<void> syncRecordMetadata(
    String? recordId, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #syncRecordMetadata,
              [recordId],
              {#executor: executor},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getPendingCount(
    String? personId, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPendingCount,
              [personId],
              {#executor: executor},
            ),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.MedicalRecord>> getReviewRecords(
    String? personId, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getReviewRecords,
              [personId],
              {#executor: executor},
            ),
            returnValue: _i3.Future<List<_i4.MedicalRecord>>.value(
              <_i4.MedicalRecord>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.MedicalRecord>>.value(
                  <_i4.MedicalRecord>[],
                ),
          )
          as _i3.Future<List<_i4.MedicalRecord>>);
}

/// A class which mocks [IImageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIImageRepository extends _i1.Mock implements _i6.IImageRepository {
  @override
  _i3.Future<List<_i7.MedicalImage>> getImagesForRecord(
    String? recordId, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getImagesForRecord,
              [recordId],
              {#executor: executor},
            ),
            returnValue: _i3.Future<List<_i7.MedicalImage>>.value(
              <_i7.MedicalImage>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i7.MedicalImage>>.value(
              <_i7.MedicalImage>[],
            ),
          )
          as _i3.Future<List<_i7.MedicalImage>>);

  @override
  _i3.Future<void> saveImages(
    List<_i7.MedicalImage>? images, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveImages, [images], {#executor: executor}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateImageTags(
    String? imageId,
    List<String>? tagIds, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateImageTags,
              [imageId, tagIds],
              {#executor: executor},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteImage(String? id, {_i5.DatabaseExecutor? executor}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [id], {#executor: executor}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateImageMetadata(
    String? imageId, {
    String? hospitalName,
    DateTime? visitDate,
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateImageMetadata,
              [imageId],
              {
                #hospitalName: hospitalName,
                #visitDate: visitDate,
                #executor: executor,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i7.MedicalImage?> getImageById(
    String? id, {
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getImageById, [id], {#executor: executor}),
            returnValue: _i3.Future<_i7.MedicalImage?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.MedicalImage?>.value(),
          )
          as _i3.Future<_i7.MedicalImage?>);

  @override
  _i3.Future<void> updateOCRData(
    String? imageId,
    String? text, {
    String? rawJson,
    double? confidence = 0.0,
    _i5.DatabaseExecutor? executor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateOCRData,
              [imageId, text],
              {#rawJson: rawJson, #confidence: confidence, #executor: executor},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ITagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITagRepository extends _i1.Mock implements _i8.ITagRepository {
  @override
  _i3.Future<List<_i9.Tag>> getAllTags({String? personId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, [], {#personId: personId}),
            returnValue: _i3.Future<List<_i9.Tag>>.value(<_i9.Tag>[]),
            returnValueForMissingStub: _i3.Future<List<_i9.Tag>>.value(
              <_i9.Tag>[],
            ),
          )
          as _i3.Future<List<_i9.Tag>>);

  @override
  _i3.Future<void> createTag(_i9.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#createTag, [tag]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTag(_i9.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#updateTag, [tag]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTag(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateOrder(List<_i9.Tag>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [tags]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.Tag>> suggestTags(String? text, {String? personId}) =>
      (super.noSuchMethod(
            Invocation.method(#suggestTags, [text], {#personId: personId}),
            returnValue: _i3.Future<List<_i9.Tag>>.value(<_i9.Tag>[]),
            returnValueForMissingStub: _i3.Future<List<_i9.Tag>>.value(
              <_i9.Tag>[],
            ),
          )
          as _i3.Future<List<_i9.Tag>>);
}
