// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/presentation/widgets/event_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:phf/core/security/encrypted_file_result.dart' as _i2;
import 'package:phf/core/security/file_security_helper.dart' as _i4;
import 'package:phf/core/services/path_provider_service.dart' as _i7;
import 'package:phf/data/models/tag.dart' as _i10;
import 'package:phf/data/repositories/interfaces/tag_repository.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEncryptedFileResult_0 extends _i1.SmartFake
    implements _i2.EncryptedFileResult {
  _FakeEncryptedFileResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_1 extends _i1.SmartFake implements _i3.File {
  _FakeFile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FileSecurityHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSecurityHelper extends _i1.Mock
    implements _i4.FileSecurityHelper {
  @override
  _i5.Future<_i2.EncryptedFileResult> encryptMedia(
    _i3.File? sourceFile, {
    required String? targetDir,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptMedia,
          [sourceFile],
          {#targetDir: targetDir},
        ),
        returnValue: _i5.Future<_i2.EncryptedFileResult>.value(
            _FakeEncryptedFileResult_0(
          this,
          Invocation.method(
            #encryptMedia,
            [sourceFile],
            {#targetDir: targetDir},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.EncryptedFileResult>.value(
            _FakeEncryptedFileResult_0(
          this,
          Invocation.method(
            #encryptMedia,
            [sourceFile],
            {#targetDir: targetDir},
          ),
        )),
      ) as _i5.Future<_i2.EncryptedFileResult>);

  @override
  _i5.Future<_i2.EncryptedFileResult> saveEncryptedFile({
    required _i6.Uint8List? data,
    required String? targetDir,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEncryptedFile,
          [],
          {
            #data: data,
            #targetDir: targetDir,
          },
        ),
        returnValue: _i5.Future<_i2.EncryptedFileResult>.value(
            _FakeEncryptedFileResult_0(
          this,
          Invocation.method(
            #saveEncryptedFile,
            [],
            {
              #data: data,
              #targetDir: targetDir,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.EncryptedFileResult>.value(
            _FakeEncryptedFileResult_0(
          this,
          Invocation.method(
            #saveEncryptedFile,
            [],
            {
              #data: data,
              #targetDir: targetDir,
            },
          ),
        )),
      ) as _i5.Future<_i2.EncryptedFileResult>);

  @override
  _i5.Future<_i3.File> decryptToTemp(
    String? encryptedPath,
    String? base64Key, {
    required String? tempDir,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptToTemp,
          [
            encryptedPath,
            base64Key,
          ],
          {#tempDir: tempDir},
        ),
        returnValue: _i5.Future<_i3.File>.value(_FakeFile_1(
          this,
          Invocation.method(
            #decryptToTemp,
            [
              encryptedPath,
              base64Key,
            ],
            {#tempDir: tempDir},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.File>.value(_FakeFile_1(
          this,
          Invocation.method(
            #decryptToTemp,
            [
              encryptedPath,
              base64Key,
            ],
            {#tempDir: tempDir},
          ),
        )),
      ) as _i5.Future<_i3.File>);

  @override
  _i5.Future<_i6.Uint8List> decryptDataFromFile(
    String? path,
    String? base64Key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptDataFromFile,
          [
            path,
            base64Key,
          ],
        ),
        returnValue: _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
        returnValueForMissingStub:
            _i5.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
      ) as _i5.Future<_i6.Uint8List>);
}

/// A class which mocks [PathProviderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathProviderService extends _i1.Mock
    implements _i7.PathProviderService {
  @override
  String get sandboxRoot => (super.noSuchMethod(
        Invocation.getter(#sandboxRoot),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sandboxRoot),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sandboxRoot),
        ),
      ) as String);

  @override
  String get dbDirPath => (super.noSuchMethod(
        Invocation.getter(#dbDirPath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#dbDirPath),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#dbDirPath),
        ),
      ) as String);

  @override
  String get imagesDirPath => (super.noSuchMethod(
        Invocation.getter(#imagesDirPath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#imagesDirPath),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#imagesDirPath),
        ),
      ) as String);

  @override
  String get tempDirPath => (super.noSuchMethod(
        Invocation.getter(#tempDirPath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#tempDirPath),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#tempDirPath),
        ),
      ) as String);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String getDatabasePath(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #getDatabasePath,
          [fileName],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDatabasePath,
            [fileName],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDatabasePath,
            [fileName],
          ),
        ),
      ) as String);

  @override
  _i5.Future<_i3.File> getSecureFile(String? relativePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecureFile,
          [relativePath],
        ),
        returnValue: _i5.Future<_i3.File>.value(_FakeFile_1(
          this,
          Invocation.method(
            #getSecureFile,
            [relativePath],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.File>.value(_FakeFile_1(
          this,
          Invocation.method(
            #getSecureFile,
            [relativePath],
          ),
        )),
      ) as _i5.Future<_i3.File>);

  @override
  _i5.Future<void> clearTemp() => (super.noSuchMethod(
        Invocation.method(
          #clearTemp,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ITagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITagRepository extends _i1.Mock implements _i9.ITagRepository {
  @override
  _i5.Future<List<_i10.Tag>> getAllTags() => (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
        ),
        returnValue: _i5.Future<List<_i10.Tag>>.value(<_i10.Tag>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i10.Tag>>.value(<_i10.Tag>[]),
      ) as _i5.Future<List<_i10.Tag>>);
}
