// Mocks generated by Mockito 5.4.6 from annotations
// in phf/test/logic/providers/person_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:phf/data/models/person.dart' as _i4;
import 'package:phf/data/repositories/app_meta_repository.dart' as _i5;
import 'package:phf/data/repositories/interfaces/person_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IPersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPersonRepository extends _i1.Mock implements _i2.IPersonRepository {
  @override
  _i3.Future<List<_i4.Person>> getAllPersons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPersons, []),
            returnValue: _i3.Future<List<_i4.Person>>.value(<_i4.Person>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Person>>.value(
              <_i4.Person>[],
            ),
          )
          as _i3.Future<List<_i4.Person>>);

  @override
  _i3.Future<void> createPerson(_i4.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#createPerson, [person]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePerson(_i4.Person? person) =>
      (super.noSuchMethod(
            Invocation.method(#updatePerson, [person]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePerson, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateOrder(List<_i4.Person>? persons) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrder, [persons]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Person?> getDefaultPerson() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultPerson, []),
            returnValue: _i3.Future<_i4.Person?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Person?>.value(),
          )
          as _i3.Future<_i4.Person?>);

  @override
  _i3.Future<_i4.Person?> getPerson(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPerson, [id]),
            returnValue: _i3.Future<_i4.Person?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Person?>.value(),
          )
          as _i3.Future<_i4.Person?>);
}

/// A class which mocks [AppMetaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppMetaRepository extends _i1.Mock implements _i5.AppMetaRepository {
  @override
  _i3.Future<String?> get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> put(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#put, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasLock() =>
      (super.noSuchMethod(
            Invocation.method(#hasLock, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setHasLock(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setHasLock, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getCurrentPersonId() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPersonId, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setCurrentPersonId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentPersonId, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isDisclaimerAccepted() =>
      (super.noSuchMethod(
            Invocation.method(#isDisclaimerAccepted, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setDisclaimerAccepted(bool? accepted) =>
      (super.noSuchMethod(
            Invocation.method(#setDisclaimerAccepted, [accepted]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getLockTimeout() =>
      (super.noSuchMethod(
            Invocation.method(#getLockTimeout, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> setLockTimeout(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setLockTimeout, [seconds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
